name: gozone

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    ports: 
      - 1234:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
        restart: true
    # command: tail -f /dev/null
