// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: factions.sql

package sqlc

import (
	"context"
)

const createFaction = `-- name: CreateFaction :one
INSERT INTO factions (
   id, created_at, updated_at, name 
) VALUES ( gen_random_uuid(), NOW(), NOW(), $1 )
RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateFaction(ctx context.Context, name string) (Faction, error) {
	row := q.db.QueryRowContext(ctx, createFaction, name)
	var i Faction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
