// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: npc.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createNpc = `-- name: CreateNpc :one
INSERT INTO npc (
  id, created_at, updated_at, name, faction_id
) VALUES ( gen_random_uuid(), NOW(), NOW(), $1, $2)
RETURNING id, created_at, updated_at, name, faction_id
`

type CreateNpcParams struct {
	Name      string
	FactionID uuid.UUID
}

func (q *Queries) CreateNpc(ctx context.Context, arg CreateNpcParams) (Npc, error) {
	row := q.db.QueryRowContext(ctx, createNpc, arg.Name, arg.FactionID)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.FactionID,
	)
	return i, err
}
